server:
  port: 9090

spring:
  datasource:
    url: jdbc:h2:mem:securevault;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    secret: ${JWT_SECRET:YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXoxMjM0NTY=}
    access-token-expiration-ms: 900000
    refresh-token-expiration-ms: 604800000
  encryption:
    master-key: ${VAULT_ENCRYPTION_KEY:YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXoxMjM0NTY=}
  rate-limit:
    login-max-attempts: 5
    login-window-minutes: 15
    pin-max-attempts: 5
    pin-window-minutes: 15
  frontend:
    url: ${FRONTEND_URL:http://localhost:5173}

logging:
  level:
    com.securevault: DEBUG
